### ISSUE TITLE
Poller initialization parameters

### ISSUE THREAD

**Issue by franfos** [algirdasc/xiaomi-ble-mqtt#18]
Hi,
I have a doubt regarding the poller initialization:
`poller = MiTempBtPoller(mac, BluepyBackend, ble_timeout=config[device].getint("timeout", 10))`
Shouldn't it be?:
`poller = MiTempBtPoller(mac, BluepyBackend, 600, 3, 'hci0', ble_timeout=config[device].getint("timeout", 10))`

Best regards.

**Comment by algirdasc** [comment]
Hi, I don't see how your change would change anything in initialization.

**Comment by franfos** [comment]
Ok, sorry, my mistake. I didn't realize you set ble_timeout. I'm used to programming languages where the order of the parameters is fixed.
